#!/bin/bash
# //====================================================
# //	System Request:Debian 9+/Ubuntu 18.04+/20+
# //	Author:	Julak Bantur
# //	Dscription: Xray MultiPort
# //	email: putrameratus2@gmail.com
# //  telegram: https://t.me/Cibut2d
# //====================================================
# // font color configuration | JULAK BANTUR AUTOSCRIPT
###########- COLOR CODE -##############
colornow=$(cat /etc/julak/theme/color.conf)
VC="\e[0m"
Green="\e[92;1m"
BICyan='\033[1;96m'
BIYellow='\033[1;93m'
COLOR1="$(cat /etc/julak/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/julak/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
y='\033[1;33m' #yellow
l='\033[0;37m'
BGX="\033[42m"
CYAN="\033[96m"
z="\033[96m"
zx="\033[97;1m" # // putih
RED='\033[0;31m'
NC='\033[0m'
gray="\e[1;30m"
Blue="\033[0;34m"
green='\033[1;32m'
grenbo="\e[92;1m"
purple="\033[1;95m"
YELL='\033[0;33m'
cyan="\033[1;36m"
c="\033[5;33m"
###########- END COLOR CODE -##########
# Getting
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://reg.scvps.biz.id/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          JULAK BANTUR AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/Cibut2d"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6281250851741"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
echo -e "\e[32mloading...\e[0m"
clear
source /var/lib/julak/ipvps.conf
if [[ "$IP" = "" ]]; then
domain=$(cat /etc/xray/domain)
else
domain=$IP
fi

#sldomain=`cat /etc/xray/dns`
#slkey=`cat /etc/slowdns/server.pub`
echo -e "$COLOR1┌─────────────────────────────────────────────────┐${NC}"
echo -e "$COLOR1 ${NC} ${COLBG1}               ${WH}• SSH PANEL MENU •              ${NC} $COLOR1 $NC"
echo -e "$COLOR1└─────────────────────────────────────────────────┘${NC}"
echo -e "$COLOR1┌─────────────────────────────────────────────────┐${NC}"
read -p "Username : " user

CLIENT_EXISTS=$(grep -w $user /etc/ssh/.ssh.db | wc -l)

  if [[ ${CLIENT_EXISTS} == '1' ]]; then
    clear
    echo -e "$COLOR1┌─────────────────────────────────────────────────┐${NC}"
    echo -e "$COLOR1 ${NC} ${COLBG1}               ${WH}• SSH PANEL MENU •              ${NC} $COLOR1 $NC"
    echo -e "$COLOR1└─────────────────────────────────────────────────┘${NC}"
    echo -e "$COLOR1┌─────────────────────────────────────────────────┐${NC}"
    echo ""
    echo "A client with the specified name was already created, please choose another name."
    echo ""
    echo -e "$COLOR1└─────────────────────────────────────────────────┘${NC}"
    read -n 1 -s -r -p "Press any key to back on menu"
    m-sshws
  fi
read -p "Password : " PASSWD
read -p "Expired (hari): " EXPIRED
read -p "Limit (IP): " iplimit

IP=$(curl -sS ifconfig.me);
sleep 1
clear
clear
clear
clear
expi=`date -d "$EXPIRED days" +"%Y-%m-%d"`
useradd -e `date -d "$EXPIRED days" +"%Y-%m-%d"` -s /bin/false -M $user
exp="$(chage -l $user | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$PASSWD\n$PASSWD\n"|passwd $user &> /dev/null
echo -e "### $user $expi $PASSWD" >> /etc/ssh/.ssh.db
PID=`ps -ef |grep -v grep | grep sshws |awk '{print $2}'`

if [[ ${c} != "0" ]]; then
  echo "${iplimit}" >/etc/ssh/${user}
fi
DATADB=$(cat /etc/ssh/.ssh.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/ssh/.ssh.db
fi
echo "### ${user} ${expi} ${iplimit} ${PASSWD}" >>/etc/ssh/.ssh.db

cat >/var/www/html/ssh-$user.txt <<END

---------------------
Format SSH OVPN Account
---------------------

Username         : $user
Password         : $PASSWD
Expired          : $exp
---------------------
IP               : $IP
Host             : $domain
Port OpenSSH     : 443, 80, 22
Port UdpSSH      : 1-65535
Port Dropbear    : 443, 109
Port Dropbear WS : 443, 109
Port SSH WS      : 80
Port SSH SSL WS  : 443
Port SSL/TLS     : 443
Port OVPN WS SSL : 443
Port OVPN SSL    : 443
Port OVPN TCP    : 443, 1194
Port OVPN UDP    : 2200
Proxy Squid 1    : 3128
Proxy Squid 2    : 8000
Proxy Squid 3    : 8080
BadVPN UDP       : 7100 - 7900
---------------------
SSH UDP : $domain:1-65535@$user:$PASSWD
---------------------
OpenVPN Config : http://$domain:81/
---------------------
Payload WSS: GET wss://$domain/ HTTP/1.1[crlf]Host: BUG[crlf]Upgrade: websocket[crlf][crlf] 
---------------------

END

TEXT="
<code>──────────────────</code>
<code>    SSH OVPN Premium Account   </code>
<code>──────────────────</code>
<code>Username        : </code> <code>$user</code>
<code>Password        : </code> <code>$PASSWD</code>
<code>Expired          : </code> <code>$exp</code>
<code>──────────────────</code>
<code>IP               : </code> <code>$IP</code>
<code>Host             : </code> <code>$domain</code>
<code>Port OpenSSH     : </code> <code>22</code>
<code>Port Dropbear    : </code> <code>109, 143</code>
<code>Port DNS         : </code> <code>80, 443,53</code> 
<code>Port SSH WS      : </code> <code>80</code>
<code>Port SSH SSL WS  : </code> <code>443</code>
<code>Port SSL/TLS     : </code> <code>443</code>
<code>Port OVPN WS SSL : </code> <code>443</code>
<code>Port OVPN SSL    : </code> <code>443</code>
<code>Port OVPN TCP    : </code> <code>443, 1194</code>
<code>Port OVPN UDP    : </code> <code>2200</code>
<code>OpenVPN CONFIG      : </code> https://$domain:81/
<code>Proxy Squid      : </code> <code>3128</code>
<code>BadVPN UDP       : </code> <code>7100 - 7900</code>
<code>───────────────────</code>
<code>SSH UDP  :</code> <code>$domain:1-65535@$user:$PASSWD</code>
<code>Payload WS   : </code> <code>GET / HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]</code>
<code>───────────────────</code>
<code>Save Link Account      : </code> https://$domain:81/ssh-$user.txt
<code>───────────────────</code>
"

curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null

if [[ ! -z "${PID}" ]]; then

clear
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1 ${NC}${COLBG1}    ${WH}• Ssh Ovpn Account •           ${NC} $COLOR1 $NC" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Host       ${COLOR1}: ${WH}$domain" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Username   ${COLOR1}: ${WH}$user"  | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Password   ${COLOR1}: ${WH}$PASSWD" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}IP               ${COLOR1}: ${WH}$IP" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Limit IP         ${COLOR1}: ${WH}${iplimit} Login" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}OpenSSH          ${COLOR1}: ${WH}22" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Dropbear         ${COLOR1}: ${WH}109, 143" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH UDP     ${COLOR1}: ${WH}1-65535" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH WS      ${COLOR1}: ${WH}80" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH WS/SSL  ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH SSL/TLS ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port Ovpn TCP    ${COLOR1}: ${WH}443,1194" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port Ovpn UDP    ${COLOR1}: ${WH}2200" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port Ovpn SSL    ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}OpenVPN Config   ${COLOR1}: ${WH}https://$domain:81/" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}UDPGW            ${COLOR1}: ${WH}7100-7900" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
#echo -e "${WH}PORT SLWDNS      ${COLOR1}: ${WH}80,22,53" | tee -a /etc/xray/log-createssh-${user}.log
#echo -e "${WH}NAMESERVER       ${COLOR1}: ${WH}$sldomain" | tee -a /etc/xray/log-createssh-${user}.log
#echo -e "${WH}PUB KEY          ${COLOR1}: ${WH}$slkey" | tee -a /etc/xray/log-createssh-${user}.log
#echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${COLOR1}Payload WS & WSS :                                      ${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}GET wss://$domain/ [protocol][crlf]Host: bug.mu[crlf]Upgrade: websocket[crlf][crlf]${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${COLOR1}SSH UDP CUSTOM   :                  ${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}$domain:1-65535@$user:$PASSWD${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${COLOR1}Save Link Account:${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}https://$domain:81/ssh-$user.txt${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Masa Aktif  ${COLOR1}: ${WH}$exp"  | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
else

echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1 ${NC}${COLBG1}    ${WH}• Ssh Ovpn Account •           ${NC} $COLOR1 $NC" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Host       ${COLOR1}: ${WH}$domain" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Username   ${COLOR1}: ${WH}$user"  | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Password   ${COLOR1}: ${WH}$PASSWD" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}IP               ${COLOR1}: ${WH}$IP" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Limit IP         ${COLOR1}: ${WH}${iplimit} Login" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}OpenSSH          ${COLOR1}: ${WH}22" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Dropbear         ${COLOR1}: ${WH}109, 143" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH UDP     ${COLOR1}: ${WH}1-65535" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH WS      ${COLOR1}: ${WH}80" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH WS/SSL  ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH SSL/TLS ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port Ovpn TCP    ${COLOR1}: ${WH}443,1194" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port Ovpn UDP    ${COLOR1}: ${WH}2200" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port Ovpn SSL    ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}OpenVPN Config   ${COLOR1}: ${WH}https://$domain:81/" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}UDPGW            ${COLOR1}: ${WH}7100-7900" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
#echo -e "${WH}PORT SLWDNS      ${COLOR1}: ${WH}80,22,53" | tee -a /etc/xray/log-createssh-${user}.log
#echo -e "${WH}NAMESERVER       ${COLOR1}: ${WH}$sldomain" | tee -a /etc/xray/log-createssh-${user}.log
#echo -e "${WH}PUB KEY          ${COLOR1}: ${WH}$slkey" | tee -a /etc/xray/log-createssh-${user}.log
#echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${COLOR1}Payload WS & WSS :                                      ${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}GET wss://$domain/ [protocol][crlf]Host: bug.mu[crlf]Upgrade: websocket[crlf][crlf]${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${COLOR1}SSH UDP CUSTOM   :                  ${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}$domain:1-65535@$user:$PASSWD${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${COLOR1}Save Link Account:${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}https://$domain:81/ssh-$user.txt${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Masa Aktif  ${COLOR1}: ${WH}$exp"  | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
fi
echo "" | tee -a /etc/log-create-user.log
read -n 1 -s -r -p "Press any key to back on menu"
m-sshws
